"""Shared fixtures.

The single most important thing in this file is the ``suite_name`` fixture:
it is parametrised over **both** AEAD configurations, and every other fixture
derives from it.  As a result each test function in this suite is collected
twice, once for AES-GCM and once for ChaCha20-Poly1305, which is what Section 6
requires ("every Testing Requirement shall be demonstrated separately using both
supported AEAD configurations").  There is no way to add a test that
accidentally covers only one configuration.
"""

from __future__ import annotations

import random
import sys
from pathlib import Path

import pytest

# Allow `python -m pytest` and plain `pytest` to work from the repository root
# without an install step, in addition to the pythonpath setting in pyproject.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from srp import (  # noqa: E402
    SUITE_NAMES,
    MaliciousActor,
    SessionPolicy,
    create_channel,
)

#: Fixed seed so that every reported failure is reproducible and the evidence in
#: the report can be regenerated byte-for-byte.
SEED = 0xC5_65_30


@pytest.fixture(params=SUITE_NAMES, ids=list(SUITE_NAMES))
def suite_name(request) -> str:
    """Each test runs once per supported AEAD configuration."""
    return request.param


@pytest.fixture
def channel(suite_name):
    """A matched sender/receiver pair over a fresh random key and session."""
    return create_channel(suite_name)


@pytest.fixture
def actor() -> MaliciousActor:
    """The malicious actor, seeded for reproducibility."""
    return MaliciousActor(random.Random(SEED))


@pytest.fixture
def small_policy() -> SessionPolicy:
    """A policy with a tiny window and record budget, for boundary tests."""
    return SessionPolicy(record_limit=16, replay_window=8)


@pytest.fixture
def payloads() -> list[bytes]:
    """A representative spread of application record sizes and contents."""
    rng = random.Random(SEED)
    return [
        b"",                                   # empty record
        b"x",                                  # single byte
        b"telemetry frame 0001",               # typical short text record
        bytes(range(256)),                     # every byte value
        rng.randbytes(64),                     # TR-8 small size
        rng.randbytes(1024),                   # TR-8 medium size
        rng.randbytes(65536),                  # TR-8 large size
    ]
